# Generated by Django 3.0.3 on 2021-07-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210727_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(blank=True, default='Syed Aareez', max_length=50),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='show',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
